services:
  my-magic-portfolio:
    build:
      dockerfile: Dockerfile
    image: magic-portfolio/my-magic-portfolio:latest
    container_name: my-magic-portfolio
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=tai.vnpsc.com,www.tai.vnpsc.com
      - VIRTUAL_PATH=/
      - LETSENCRYPT_HOST=tai.vnpsc.com,www.tai.vnpsc.com
      - LETSENCRYPT_EMAIL=spinatp@gmail.com  # email to encrypt information
    # ports:
    #   - "3001:3001"   # optional
    networks:
      shared:
        aliases:
          - my-magic-portfolio
    restart: always
networks:
  shared:
    external: true
    name: my_tailt_shared_net