name: "Build and deploy my portfolio to server"

on:
  push:
    branches:
      - feature/final

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.ONLINE_HOST }} # ip of server
          username: ${{ secrets.ONLINE_USERNAME }} # Username to login to server
          key: ${{ secrets.ONLINE_SSH_PRIVATE_KEY }} # Private key to login to server

          script: |
            set -e

            docker container stop my-magic-portfolio || true

            docker container remove my-magic-portfolio || true

            docker image remove magic-portfolio/my-magic-portfolio:latest || true

            cd ${{ secrets.ONLINE_PATH_PROJECT }} 

            if [ -d my-magic-portfolio ]; then
              cd my-magic-portfolio
              git fetch 
              git pull
            else
              git clone -b feature/final https://github.com/astropop/my-magic-portfolio.git
              cd my-magic-portfolio
            fi

            cd fe

            docker compose build
            docker compose up -d
